#!/bin/python3

if __name__ == '__main__':
    a = int(input())
    b = int(input())
    if 1 <= (a and b) <= 10**10:
        print(a + b)
        print(a - b)
        print(a * b)
    else:
        exit()
